### PR TITLE
passes cache_spec=False to nwb_io.write() to avoid spec writer shape …

### LINKED ISSUE #404: Ephys NWB "Shapes do not match" error in feature extraction
Running ipfx feature extraction on ephys data for June about 90% fail with this error:

```
Traceback (most recent call last):
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/ipfx/bin/run_pipeline_from_nwb_file.py", line 59, in <module>
    main()
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/ipfx/bin/run_pipeline_from_nwb_file.py", line 53, in main
    pipeline_input["manual_sweep_states"])
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/ipfx/bin/run_pipeline.py", line 59, in run_pipeline
    se_output['cell_features'],
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/ipfx/bin/run_feature_extraction.py", line 74, in run_feature_extraction
    output_nwb_path=output_nwb_file)
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/ipfx/nwb_append.py", line 61, in append_spike_times
    nwb_io.write(nwbfile)
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/hdmf/utils.py", line 483, in func_call
    return func(args[0], **parsed['args'])
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/hdmf/backends/hdf5/h5tools.py", line 297, in write
    ns_builder.export('namespace', writer=writer)
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/hdmf/utils.py", line 483, in func_call
    return func(args[0], **parsed['args'])
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/hdmf/spec/write.py", line 213, in export
    writer.write_spec(out, path)
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/hdmf/backends/hdf5/h5_utils.py", line 280, in write_spec
    return self.__write(spec, path)
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/hdmf/backends/hdf5/h5_utils.py", line 276, in __write
    dset = self.__group.require_dataset(name, shape=tuple(), data=data, dtype=self.__str_type)
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/h5py/_hl/group.py", line 198, in require_dataset
    raise TypeError("Shapes do not match (existing %s vs new %s)" % (dset.shape, shape))
TypeError: Shapes do not match (existing (1,) vs new ())
```

Running this with a test file at:
/allen/aibs/technology/waynew/ephys/features/troubleshoot_392647.05.02.01/dev.pbs

### PR DESCRIPTION
**Pull request by MatthewAitken**
Resolve #404 …error

### CODE REVIEW

**Comment by t-b** [comment]
Is it really required to not cache the spec? Caching the specification should always be done in order to ensure that the files can be validated later on.

**Comment by MatthewAitken** [comment]
> Is it really required to not cache the spec? Caching the specification should always be done in order to ensure that the files can be validated later on.

@t-b When we write the file after adding the spike times, during the spec update in H5SpecWriter (https://github.com/hdmf-dev/hdmf/blob/dev/src/hdmf/backends/hdf5/h5_utils.py#L276) H5py's self.__group.require_dataset(name, shape=tuple(), data=data, dtype=self.__str_type) is called with the shape=tuple() argument. But the preexisting dataset has shape (1,), so it errors out instead keeping the old spec. This is just a temporary fix right now, and we do want to update the spec when we write nwb files. I'm opening an issue on pynwb.

**Comment by wbwakeman** [comment]
Will this change be used by ipfx.attach_metadata?
(i.e. when I do feature extraction with bin/run_pipeline_from_nwb_file.py it works, but when I try to attach metadata I still get the "Shapes do not match" error)

**Comment by sgratiy** [comment]
@wbwakeman have skipping spec update in the attach_metadata module fixed the issue with metadata attachment?

**Comment by wbwakeman** [comment]
@sgratiy  Yes, I can attach metadata now

**Comment by sgratiy** [comment]
@MatthewAitken I could not see the issue open on pynwb as mentioned above. I wanted to link it to this issue.
Are we ready to merge this PR?

**Comment by wbwakeman** [comment]
@MatthewAitken  I discussed this with @t-b  and he had some good thoughts on the issue.  The NWB2 files that I am working with for the June release are being written by MIES and include a cached_specification already.  When  ipfx attach_metadata and append_spike_times write the NWB2 file, they are also attempting to cache the spec again.  This causes the "Shapes do not match" error. 

This PR solves that problem by not caching the spec again, which leaves the one written by MIES. Another approach (thanks @t-b ) would be to remove the MIES one. That can be done with something like

```
import h5py
with h5py.File("HardwareTests-V2.nwb", mode="r+") as f:
    for spec in ['/specifications/core', '/specifications/hdmf-common']:
        if spec in f:
            del f[spec]
```

What do you think about following this strategy to correct the problem?

**Comment by wbwakeman** [comment]
This may be unnecessary once this PR is merged?
https://github.com/hdmf-dev/hdmf/pull/346

**Pull request closed without merging**
