### PR TITLE
Add EphysDataset derived class

### LINKED ISSUE #107: Add support for reading NWBv2 and execute the pipeline on them
- Inherit from EphysDataset, AibsDataset is an example which reads MIES data
- Add tests a la test_ephys_data_set.py

- [x] EphysDataSet should be NWb agnostic
- [x] Move `Sweep` instance creation into NWB reader 

Stick with python 2.7 for now.

The full pipeline can be run with run_pipeline.py.

### PR DESCRIPTION
**Pull request by t-b**
Closes #107.

The new class is currently called `HBGDataSet`.

### CODE REVIEW

**Comment by dyf** [comment]
@t-b what does HBG stand for?

**Comment by t-b** [comment]
**H**uman**B**rain**G**rant. There exists certainly better names ;)

**Comment by t-b** [comment]
@dyf @sgratiy Ready for review

The pipeline script does bug out as the stimset name is not found:

```
$ ./pipeline_from_nwb_file.sh ../../Jim\ Berg\ Tests/From_abf/H18.29.135.11.41.01.nwb
E:\projekte\allensdk.ipfx\ipfx\bin\lims_queries.py:7: UserWarning: Can not import LIMS libraries due to 'No module named internal.core.lims_
utilities', using default values.
  warnings.warn("Can not import LIMS libraries due to '%s', using default values." % e)
WARNING:root:many=True not supported from argparse
DEBUG:root:loading default stimulus ontology: e:\projekte\allensdk.ipfx\ipfx\defaults/stimulus_ontology.json
DEBUG:root:Build sweep table
Traceback (most recent call last):
  File "run_pipeline.py", line 78, in <module>
    if __name__ == "__main__": main()
  File "run_pipeline.py", line 71, in main
    module.args.get("manual_sweep_states", None))
  File "run_pipeline.py", line 23, in run_pipeline
    stimulus_ontology_file)
  File "E:\projekte\allensdk.ipfx\ipfx\bin\run_sweep_extraction.py", line 39, in run_sweep_extraction
    ontology=ont)
  File "e:\projekte\allensdk.ipfx\ipfx\data_set_utils.py", line 25, in create_data_set
    ontology=ontology, api_sweeps=api_sweeps)
  File "e:\projekte\allensdk.ipfx\ipfx\hbg_dataset.py", line 18, in __init__
    sweep_info = self.extract_sweep_meta_data()
  File "e:\projekte\allensdk.ipfx\ipfx\hbg_dataset.py", line 64, in extract_sweep_meta_data
    sweep_record["stimulus_name"] = self.get_stimulus_name(sweep_record["stimulus_code"])
  File "e:\projekte\allensdk.ipfx\ipfx\ephys_data_set.py", line 199, in get_stimulus_name
    stim = self.ontology.find_one(stim_code, tag_type="code")
  File "e:\projekte\allensdk.ipfx\ipfx\stimulus.py", line 80, in find_one
    matching_stims = self.find(tag, tag_type)
  File "e:\projekte\allensdk.ipfx\ipfx\stimulus.py", line 75, in find
    raise KeyError("Could not find stimulus: %s" % tag)
KeyError: u'Could not find stimulus: EXTPINBATH_IN1'
```

**Comment by dyf** [comment]
Thanks @t-b.  We basically need to either a) get collaborators to use codes already in our ontology (in this particular case, `EXTPINBATH` or `EXTPINBATH141203` would work), or to add the new codes to the file.  Do you have any idea why the `_IN1` postfix was added?

**Comment by t-b** [comment]
@dyf I can't really decide if `a` or `b` is good, but in general `a` sounds better. The full path of the protocol is `C:\Allen Institute\Allen Institute protocols with text attachment\IN1\EXTPINBATH_IN1.pro` and the name of this file without suffix is used for the stimulus set name. The `_IN1` postfix looks like the input channel. As they encode the input channel also in one of the folder names this postfix could be dropped.

**Comment by t-b** [comment]
> If you want to handle dropping the postfix during conversion in a separate PR that's fine.

I'll do that, I just missed the fact that we settled on this solution.

**Pull request merged**
