### PR TITLE
Feature/store as fp32

### LINKED ISSUE #149: X-NWB: Create TimeSeries datasets with FP32 type in NWB v2

### PR DESCRIPTION
**Pull request by t-b**
Closes #149.

See also https://github.com/NeurodataWithoutBorders/pynwb/issues/795.

### CODE REVIEW

**Comment by t-b** [comment]
@sgratiy I certainly can rename `utils.py`. I'm just wondering why you think this is useful. It is in the module `x_to_nwb` so all users already include it as

https://github.com/AllenInstitute/ipfx/blob/c24bc153a1def8c940e68ae751dd485aab1aed84/ipfx/x_to_nwb/ABFConverter.py#L15-L18

and that seems unambigous or?

**Comment by sgratiy** [comment]
@t-b giving a more specific name would help me better understand the purpose of the module. This makes code a bit more transparent. Right now I am not quite sure what is common to all the functions in this module, but this is not a big deal :)

**Comment by t-b** [comment]
@sgratiy Sure, I'll rename then and add some file level comments.

**Comment by t-b** [comment]
@sgratiy Done.

**Comment by sgratiy** [comment]
@t-b Looks good!

**Pull request merged**
